#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias emacs="$EMACS_PLUGIN_LAUNCHER --no-wait"
alias e=emacs
# open terminal emacsclient
alias te="$EMACS_PLUGIN_LAUNCHER -nw"
# same than M-x eval but from outside Emacs.
alias eeval="$EMACS_PLUGIN_LAUNCHER --eval"
# create a new X frame
alias eframe='emacsclient --alternate-editor "" --create-frame'

# Set the prompt
# prompt sorin
eval "$(starship init zsh)"
# export RPROMPT=''

# Custom aliases
# A few aliases for exa, a ls replacement
alias l="exa --sort Name --classify"
alias lb="exa --sort size --long --classify --reverse"
alias ll="exa --sort Name --long --classify"
alias la="exa --sort Name --long --classify --all"
alias lr="exa --sort Name --long --classify --recurse"
alias lra="exa --sort Name --long --classify --recurse --all"
alias lt="exa --sort Name --long --classify"
alias lta="exa --sort Name --long --tree --all --classify"
alias ls="exa --sort Name --classify"
alias lrt="exa --long -snew --classify"

# Other common aliases
alias cat='bat'

# Pipe Aliases
## Pipe Aliases (Global)
alias -g L='|less'
alias -g G='|grep'
alias -g T='|tail'
alias -g H='|head'
alias -g W='|wc -l'
alias -g S='|sort'

## Proxy variables

# Set and unset the proxy servers.
function proxyon(){
  export http_proxy="http://proxy-iind.intel.com:911"
  export https_proxy="http://proxy-iind.intel.com:911"
  export ftp_proxy="http://proxy-iind.intel.com:911"
  export socks_proxy="http://proxy-iind.intel.com:1080"
  # export ALL_PROXY='socks5://proxy-iind.intel.com:1080'
  export no_proxy="intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127,0.0.1,127.0.0.0/8,134.134.0.0/16"
  # echo -e "\nProxy environment variable set."
}
function proxyoff(){
  unset HTTP_PROXY
  unset http_proxy
  unset HTTPS_PROXY
  unset https_proxy
  unset FTP_PROXY
  unset ftp_proxy
  unset socks_proxy
  unset ALL_PROXY
  unset no_proxy
  # echo -e "\nProxy environment variable removed."
}

# Jupyter Notebook remote
alias port_forward='nohup ssh -N -f -L localhost:8890:localhost:8890 vikasm@192.168.1.225'
alias remote_notebook_start_tf='nohup ssh -f vikasm@192.168.1.225 ". /home/vikasm/anaconda3/etc/profile.d/conda.sh; conda activate tensorflow; jupyter lab --no-browser --port=8890"; port_forward'
alias remote_notebook_start_torch='nohup ssh -f vikasm@192.168.1.225 ". /home/vikasm/anaconda3/etc/profile.d/conda.sh; conda activate torch; jupyter lab --no-browser --port=8890"; port_forward'
alias remote_notebook_stop='ssh vikasm@192.168.1.225 "pkill -u vikasm jupyter"'

# My Fasd aliases
alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias d='fasd -d'        # directory
alias f='fasd -f'        # file
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias z='fasd_cd -d'     # cd, same functionality as j in autojump
alias zz='fasd_cd -d -i' # cd with interactive selection

# Timezsh - to benchmark how long zsh takes to load
timezsh() {
  shell=${1-$SHELL}
  for i in $(seq 1 10); do /usr/bin/time $shell -i -c exit; done
}

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/vikasmis/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/vikasmis/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/vikasmis/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/vikasmis/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


# Local Variables:
# mode: sh
# End:
